Core/urls.py
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path, reverse_lazy
from Core.views import home, stats, upload


app_name = 'core'

urlpatterns = [
    path('', home.homepage_view, name="home"),
    path('login/', LoginView.as_view(template_name='Core/auth_login.html', extra_context={'title': 'Anmelden'}), name='login'),
    path('logout/', LogoutView.as_view(template_name='Core/auth_logout.html'), name='logout'),
    path('password-change/', PasswordChangeView.as_view(template_name='Core/auth_password_change.html', success_url=reverse_lazy('core:password-change-done')), name='password-change'),
    path('password-changed/', PasswordChangeDoneView.as_view(template_name='Core/auth_password_change_done.html'), name='password-change-done'),
    path('statistics/', stats.view, name="stats"),
    path('upload/', upload.upload_view, name="upload"),
]

HallCam/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Core.urls')),
    path('admin/', admin.site.urls),
]


# https://docs.djangoproject.com/en/3.2/ref/views/#serving-files-in-development
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Core/models.py
from django.core.files.storage import default_storage
from django.db import models
from pathlib import Path
from PIL import Image

from Accounts.models import User


class Camera(models.Model):
    name  = models.CharField(max_length=40, unique=True)
    pwd   = models.CharField(max_length=80, verbose_name="password", help_text="The password that the camera must use in the picture upload form.")
    scene = models.CharField(max_length=80)
    notes = models.CharField(max_length=80, blank=True)
    users = models.ManyToManyField(User, blank=True, help_text="Who can see this camera's pictures?")

    def __str__(self):
        return f"{self.name} ({self.scene})"


class Picture(models.Model):
    """A picture is a photo of a scene along with related metadata."""

    PICTURES_SUBDIR = 'pictures'
    THUMBNAILS_SUBDIR = 'thumbs'
    VALID_SUFFIXES = ('.jpg', '.png', '.gif', '.jpeg')

    EVENT_CHOICES = [
        ('scheduled', ''),
        ('manual', 'ssh or local terminal'),
        ('img analysis', ''),
        ('motion_detection', ''),
        ('other', 'other'),
    ]

    camera    = models.ForeignKey(Camera, models.PROTECT, help_text="The camera that has taken the picture.")
    filename  = models.CharField(max_length=48, unique=True)
    timestamp = models.DateTimeField(help_text="The time at which the camera took the picture.")
  # event     = models.CharField(max_length=12, choices=EVENT_CHOICES, help_text="The event that triggered the capture of this picture.")
  # quality   = Cam_original, cam_upload, thumbnail
  # temperature, time-to-upload, …

    def get_image_url(self):
        return default_storage.base_url + f"{self.PICTURES_SUBDIR}/camera-{self.camera_id}/{self.filename}"

    def get_thumb_url(self):
        pic_path   = Path(default_storage.location, self.PICTURES_SUBDIR,   f"camera-{self.camera_id}", self.filename)
        thumb_path = Path(default_storage.location, self.THUMBNAILS_SUBDIR, f"camera-{self.camera_id}", self.filename).with_suffix('.jpg')

        # print("get_thumb_url()")
        # print(f"--> {pic_path = }")
        # print(f"--> {pic_path.exists() = }")
        # print(f"--> {thumb_path = }")
        # print(f"--> {thumb_path.exists() = }")

        # If the thumbnail image does not yet exist, create it now.
        if not thumb_path.exists():
            # If this is the first picture of a new camera, make sure that
            # the related subdirectory exists.
            thumb_path.parent.mkdir(parents=True, exist_ok=True)

            try:
                with Image.open(pic_path) as img:
                    if img.mode != 'RGB':
                        # Make sure that PNG images with a palette are converted to RGB.
                        img = img.convert('RGB')
                    img.thumbnail((400, 300), resample=Image.LANCZOS)
                    img.save(thumb_path, 'JPEG')
            except FileNotFoundError as e:
                print("Picture.get_thumb_url() --> ", e)

        return default_storage.base_url + str(thumb_path.relative_to(default_storage.location))

    class Meta:
        ordering = ['timestamp']

Core/views/home.py
from datetime import timedelta
from django.db import transaction
from django.shortcuts import render
from django.utils import timezone

from Accounts.models import User
from Core.models import Camera


def get_latest_and_24(cameras):
    """Returns the latest picture and those of the last 24 hours at the full hour."""
    collages = []
    now = timezone.now()

    # The latest full hour is `floor(now)` (with regards to hours),
    # the first full hour is 23 hours before that.
    latest_fh = now.replace(minute=0, second=0, microsecond=0)
    first_fh = latest_fh - timedelta(hours=23)

    for cam in cameras:
        pics = list(cam.picture_set.filter(timestamp__gte=first_fh-timedelta(minutes=30)))
        series = [None] * 24

        for pic in pics:
            delta = (pic.timestamp - first_fh).total_seconds() / 3600.0
            index = round(delta)

            if not (0 <= index < 24):
                continue

            if series[index] is None:
                series[index] = pic
                continue

            old_delta = (series[index].timestamp - first_fh).total_seconds() / 3600.0
            assert round(old_delta) == index

            if abs(index - delta) < abs(index - old_delta):
                series[index] = pic

        collage = {
            'camera': cam,
          # 'latest': cam.picture_set.all().order_by('timestamp')[0],
            'latest': pics[-1] if pics else None,
            'series': series,
        }
        collages.append(collage)

    return collages


def get_all_of_last_24_hours(cameras):
    now = timezone.now()
    cam_pics = []

    for cam in cameras:
        pics = cam.picture_set.filter(timestamp__gte=now - timedelta(days=1))
        cam_pics.append(
            {
                'camera': cam,
                'pictures': list(pics),   # this must be a list, or we can only iterate it once
            },
        )

    return cam_pics


@transaction.non_atomic_requests
def homepage_view(request):
    if request.user.is_authenticated:
        cameras = request.user.camera_set.all()
    else:
        try:
            public_user = User.objects.get(email="public_user@cafu.de", is_active=False)
            cameras = public_user.camera_set.all()
        except User.DoesNotExist:
            cameras = Camera.objects.none()

    layout = request.GET.get('layout')
    context = {}

    if layout == 'all-of-24h':
        context['title'] = "Details"
        context['subtitle'] = "Alle Bilder der letzten 24 Stunden"
        context['cam_pics'] = get_all_of_last_24_hours(cameras)
    else:
        context['title'] = "Übersicht"
        context['subtitle'] = "Das aktuelle Bild und die letzten 24 Stunden"
        context['collages'] = get_latest_and_24(cameras)

    return render(request, "Core/home.html", context)

Core/views/stats.py
from io import StringIO
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from Core.libs.pictures import cleanup_pictures, sync_pictures


@staff_member_required
def view(request):

    with StringIO() as buffer:
        cleanup_pictures(hot_run=False, out=buffer)
        cleanup_report = buffer.getvalue()

    return render(
        request,
        'Core/stats.html',
        {
            'title': "Statistics 📈",
            'stats': sync_pictures(hot_run=False, verbosity=0),
            'cleanup_report': cleanup_report,
        },
    )

Core/views/upload.py
from backports.zoneinfo import ZoneInfo
from datetime import datetime
from pathlib import Path

from django.conf import settings
from django.shortcuts import redirect, render
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django import forms

from Core.models import Camera, Picture


class UploadPictureForm(forms.Form):
    camera   = forms.ModelChoiceField(queryset=Camera.objects.all(), to_field_name="name")
    password = forms.CharField(max_length=40)
    pic_file = forms.ImageField()
  # sys_info = forms.CharField(max_length=250, required=False)

    def clean(self):
        cd = super().clean()

        # Setze hier gar nicht erst an, solange es noch Felder gibt, die in sich fehlerhaft sind.
        if self.errors:
            return

        if cd['password'] != cd['camera'].pwd:
            self.add_error('password', "The password is wrong.")
            return cd

        return cd


def save_to_disk(camera, uploaded_pic_file):
    """Saves the given `UploadedFile` to disk and returns its full path."""

    pic_path = Path(
        settings.MEDIA_ROOT,
        Picture.PICTURES_SUBDIR,
        f"camera-{camera.id}",
        uploaded_pic_file.name,
    )

    # If this is the first picture of a new camera, make sure that
    # the related subdirectory exists.
    pic_path.parent.mkdir(parents=True, exist_ok=True)

    with open(pic_path, 'wb') as dest_file:
        for chunk in uploaded_pic_file.chunks():
            dest_file.write(chunk)

    print(f"Picture saved to {pic_path} ({uploaded_pic_file.content_type}, {uploaded_pic_file.size} bytes, camera {camera.name})")
    return pic_path


@csrf_exempt
def upload_view(request):
    # The basics of this view are explained at
    # https://docs.djangoproject.com/en/4.0/topics/http/file-uploads/

    if request.method == 'POST':
        # The items in `request.FILES` are of type `UploadedFile`. For details,
        # see https://docs.djangoproject.com/en/4.0/ref/files/uploads/
        form = UploadPictureForm(request.POST, request.FILES)

        if form.is_valid():
            # The `ImageField` in the form normalizes to an `UploadedFile` object.
            # This is just the `UploadedFile` taken from request.FILES['pic_file'],
            # augmented with an additional `image` attribute as described at
            # https://docs.djangoproject.com/en/4.0/ref/forms/fields/#imagefield
            assert form.cleaned_data['pic_file'] == request.FILES['pic_file']

            pic_path = save_to_disk(form.cleaned_data['camera'], form.cleaned_data['pic_file'])

            try:
                dt = datetime.strptime(pic_path.name[4:17], "%Y%m%d_%H%M")
                dt = dt.replace(tzinfo=ZoneInfo('Europe/Berlin'))
            except ValueError:
                dt = timezone.now()

            # If a picture with the given filename already exists, the file on
            # disk is overwritten and the related `Picture` object is updated
            # rather than created (the `filename` must be unique).
            Picture.objects.update_or_create(
                filename=pic_path.name,
                defaults={
                    'camera': form.cleaned_data['camera'],
                    'timestamp': dt,
                }
            )

            return redirect('core:upload')
    else:
        form = UploadPictureForm()

    return render(request, 'Core/upload.html', {
        'title': "Upload image 😜",
        'form': form,
    })

Core/templates/Core/auth_login.html
{% extends "Core/bs5_base.html" %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col" style="max-width: 600px;">
            <form method="post" novalidate>
                <div class="card shadow-sm">
                    <img src="{% static 'Core/Halle-2-1314.jpg' %}" class="card-img-top" alt="Willkommen!">
                    <div class="card-body px-4 pt-4 pb-0">
                        {% csrf_token %}
                        {% include 'Core/inc_bs5_form_simple.html' with form=form only %}
                    </div>
                    <div class="card-footer border-top-0 px-4 py-3">
                        <button type="submit" class="btn btn-primary">Anmelden</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Core/templates/Core/auth_logout.html
{% extends "Core/bs5_base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col" style="max-width: 600px;">
            <div class="card shadow-sm">
                <img src="{% static 'Core/Halle-1-2016.jpg' %}" class="card-img-top" alt="Bis bald!">
                <div class="card-body px-4 pt-4 pb-0">
                    {# <h1 class="card-title">{{ title }}</h1> #}
                    <p class="mb-4">{% trans "Thanks for spending some quality time with the web site today." %}</p>
                </div>
                <div class="card-footer border-top-0 px-4 py-3">
                    <a class="btn btn-primary" href="{% url 'core:login' %}">{% trans 'Log in again' %}</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Core/templates/Core/auth_password_change.html
{% extends "Core/bs5_base.html" %}
{% load i18n %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col" style="max-width: 600px;">
            <p style="color: var(--bs-gray);">
                Hier können Sie das Passwort ändern, mit dem Sie sich (zusammen mit Ihrem Benutzernamen) bei Lori anmelden.
                Geben Sie dazu zuerst Ihr altes Passwort ein, anschließend zweimal das neue.
            </p>
            <form method="post" novalidate>
                <div class="card border-0 shadow-sm">
                    <div class="card-body px-4 pt-4 pb-0">
                        {% csrf_token %}
                        {% include 'Core/inc_bs5_form_simple.html' with form=form only %}
                    </div>
                    <div class="card-footer border-top-0 px-4 py-3">
                        <button type="submit" class="btn btn-primary">Passwort ändern</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

Core/templates/Core/auth_password_change_done.html
{% extends "Core/bs5_base.html" %}
{% load i18n %}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col" style="max-width: 640px;">
            <div class="alert alert-success mt-5" role="alert">
                {% trans 'Your password was changed.' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

Core/templates/Core/bs5_base.html
<!DOCTYPE html>
{% load static %}
<html lang="{{ LANGUAGE_CODE|default:'en' }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="google" content="notranslate">{# Keep Chrome from bothering the user about translations. #}
    <meta name="robots" content="NONE,NOARCHIVE">

    <link rel="icon" type="image/png" href="{% static 'Core/favicon.png' %}">
    <link rel="stylesheet" href="https://bootswatch.com/5/darkly/bootstrap.min.css">

    <style>
        nav.navbar {
            /* padding-top: 0.5rem; */
        }

        nav.navbar a.navbar-brand > img.Halle {
            height: 60px;
            width: 60px;
        }
    </style>

    {% block extrastyle %}{% endblock %}
    {% block extrahead %}{% endblock %}

    <title>{% block title %}{{ title|default:"Welcome" }}{% endblock %}{% if user.profile %} - {{ user.profile.ma.str_individual }}{% endif %} - HallCam</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark pt-2 pb-2">
        <div class="container-fluid px-lg-5">
            <a class="navbar-brand py-0 me-4" href="{% url 'core:home' %}"><img class="rounded-circle Halle" src="{% static 'Core/Halle-1-640.jpg' %}" alt="Halle"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#id_navbarNav" aria-controls="id_navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="id_navbarNav">
                {% if user.is_active %}
                    <ul class="navbar-nav nav-pills me-auto">
                        <li class="nav-item">
                            <a class="nav-link me-3 {# active #}" {# aria-current="page" #} href="{% url 'core:home' %}">Übersicht</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link me-3 dropdown-toggle" href="#" id="id_DetailsMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">Details</a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="id_DetailsMenu">
                                <li><a class="dropdown-item" href="{% url 'core:home' %}?layout=all-of-24h">Alle Bilder der letzten 24 Stunden{# Last 24 hours in steps of 5 minutes #}</a></li>
                            </ul>
                        </li>
                        {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link me-3" href="{% url 'core:stats' %}">Statistics{# 📈 #}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-3" href="{% url 'core:upload' %}">Upload</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-3" href="{% url 'admin:index' %}">Admin</a>
                        </li>
                        {% endif %}
                    </ul>

                    <ul class="navbar-nav nav-pills">
                        <li class="nav-item dropdown">
                            <a class="nav-link ms-3 pe-0 dropdown-toggle" href="#" id="id_UserMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                <img class="rounded-circle gravatar" src="{{ user.get_gravatar_url }}?s=22" style="width: 22px; height: 22px;" alt="">
                                {{ user.short_name }}</a>
                            <ul class="dropdown-menu dropdown-menu-dark dropdown-menu-end" aria-labelledby="id_UserMenu">
                                {% if user.has_usable_password %}
                                    <li><a class="dropdown-item" href="{% url 'core:password-change' %}">Passwort ändern</a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'core:logout' %}">Abmelden</a></li>
                            </ul>
                        </li>
                    </ul>
                {% else %}
                    <div class="navbar-nav nav-pills ms-auto">
                        <a class="nav-link" href="{% url 'core:login' %}">Anmelden</a>
                    </div>
                {% endif %}
            </div>
        </div>
    </nav>

    <main>
        {% block headline %}
            {% if title or user.profile %}
            <div class="container-fluid shadow-sm px-lg-5 py-4 mb-5" style="background-color: #232323;">
                <div class="row">
                    {% if title %}
                        <div class="col">
                            <h1 class="my-0 text-center">{{ title }}</h1>
                            {% if subtitle %}<p class="mt-2 mb-0 lead text-center text-muted">{{ subtitle }}</p>{% endif %}
                        </div>
                    {% endif %}
                    {% if user.profile %}
                        <div class="col align-self-center">
                            <h2 class="lead text-muted text-end my-0">{{ user.profile.ma.str_individual }}</h2>
                        </div>
                    {% endif %}
                </div>
            </div>
            {% endif %}
        {% endblock %}
        {% block messages %}
            {% if messages %}
                <div class="container">
                {% for message in messages %}
                    <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags|default:'info' }}{% endif %} alert-dismissible" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        {{ message|capfirst }}
                    </div>
                {% endfor %}
                </div>
            {% endif %}
        {% endblock %}

        {% block content %}{% endblock %}
    </main>

    {% block footer %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% block extrascript %}{% endblock %}
</body>
</html>

Core/templates/Core/home.html
{% extends "Core/bs5_base.html" %}
{% load static %}

{% block extrastyle %}
    <link rel="stylesheet" href="{% static 'glightbox/css/glightbox.css' %}">
{% endblock %}

{% block extrascript %}
    <script src="{% static 'glightbox/js/glightbox.min.js' %}"></script>
    <script>
        const lightbox = GLightbox({
            slideEffect: 'fade',
        });
    </script>
{% endblock %}

{% block content %}

{% if collages is not None %}
<div class="container-fluid">
    {% for collage in collages %}
        <h2 class="text-center mt-5"><small>{{ collage.camera.name }}</small></h2>
        <p class="lead text-muted text-center">{{ collage.camera.scene }}</p>

        {% if collage.latest %}
            <div class="row gx-2 gy-2 mt-3">{# `gy-*` is relevant for narrow screens when the two main columns are stacked. #}
                <div class="col-xl-6">
                    <div class="row row-cols-2 row-cols-sm-4 row-cols-md-4 row-cols-lg-6 row-cols-xl-4 row-cols-xxl-6 gx-0 gy-2">
                        {% for pic in collage.series %}
                            <div class="col">
                                <div class="card">
                                    {% if pic %}
                                        <a class="glightbox" href="{{ pic.get_image_url }}"><img class="card-img-top" src="{{ pic.get_thumb_url }}" alt="image"></a>
                                    {% endif %}
                                    <div class="card-body p-0">
                                        <p class="card-text text-center text-muted small">{{ pic.timestamp|date:"H:i"|default:'kein Bild' }}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-xl-6">
                    <img class="img-fluid" src="{{ collage.latest.get_image_url }}" alt="image">
                </div>
            </div>
        {% else %}
            <p class="text-center text-muted">Es sind keine Bilder vorhanden.</p>
        {% endif %}
    {% empty %}
        <p class="text-center text-muted">Es sind keine Bilder vorhanden.</p>
    {% endfor %}
</div>
{% endif %}

{% if cam_pics is not None %}
<div class="container-fluid">
    {% for cp_set in cam_pics %}
        <h2 class="text-center mt-5"><small>{{ cp_set.camera.name }}</small></h2>
        <p class="lead text-muted text-center">{{ cp_set.camera.scene }}</p>

        {% if cp_set.pictures %}
            <div class="row gx-0 gy-2">
                {% for pic in cp_set.pictures %}
                    <div class="col-6 col-sm-4 col-md-3 col-lg-2 col-xl-2 col-xxl-1">
                        <div class="card">
                            {% if pic %}
                                <a class="glightbox" href="{{ pic.get_image_url }}"><img class="card-img-top" src="{{ pic.get_thumb_url }}" alt="image"></a>
                            {% endif %}
                            <div class="card-body p-0">
                                <p class="card-text text-center text-muted small">{{ pic.timestamp|date:"H:i"|default:'kein Bild' }}</p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p class="text-center text-muted">Es sind keine Bilder vorhanden.</p>
        {% endif %}
    {% empty %}
        <p class="text-center text-muted">Es sind keine Bilder vorhanden.</p>
    {% endfor %}
</div>
{% endif %}

{% endblock %}

Core/templates/Core/inc_bs5_form_simple.html
{% load widget_tweaks %}

{% comment %}
    This template renders the fields in Bootstrap's default layout:
    Each input field is 100 % wide and its label is above.

    Some guidance for this template was taken from
    https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html
{% endcomment %}

{% if form.errors and not form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        Beim Verarbeiten des Formulars sind Fehler aufgetreten.
        Bitte beheben Sie die unten aufgeführten Probleme und senden Sie das Formular erneut.
    </div>
{% endif %}

{% for error in form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
{% endfor %}

{% for hidden_field in form.hidden_fields %}
    {% for error in hidden_field.errors %}
        <div class="alert alert-danger" role="alert">
            Fehler im verborgenen Feld „{{ hidden_field.label }}“: {{ error }}
        </div>
    {% endfor %}
    {{ hidden_field }}
{% endfor %}

{% comment %}
    {# TODO: Wie integriert man das am besten in die allg. Schleife unten? #}
    {% if field.field.widget.input_type == "checkbox" %}
        <div class="mb-3 form-check">
            {{ field|add_class:"form-check-input" }}
            {# The following yields what we would have expected from `field.label_tag|add_class:"…"` #}
            {{ field|add_label_class:"form-check-label" }}
        </div>
    {% else %}
        ...
    {% endif %}
{% endcomment %}

{% for field in form.visible_fields %}
    {# TODO 1: checkboxes, see above #}
    {# TODO 2: datepicker support (note: input groups require an additional .has-validation class) #}

    <div class="mb-4">
        {# The following yields what we would have expected from `field.label_tag|add_class:"…"` #}
        {{ field|add_label_class:"form-label" }}

        {% if field.errors %}
            {{ field|add_class:"form-control is-invalid" }}
        {% elif form.is_bound %}
            {{ field|add_class:"form-control" }}{# We might add "is-valid" here, but I think it is confusing. #}
        {% else %}
            {{ field|add_class:"form-control" }}
        {% endif %}

        {% for error in field.errors %}
            <div class="invalid-feedback">{{ error }}</div>
        {% endfor %}

        {% if field.help_text %}
            <div class="form-text">{{ field.help_text }}</div>
        {% endif %}
    </div>
{% endfor %}

Core/templates/Core/stats.html
{% extends "Core/bs5_base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <h2>Database sync</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-2">
            <table class="table table-striped table-dark pic_stats">
                <thead>
                    <tr>
                        <th scope="col">Pictures</th>
                        <th scope="col">pictures/*</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ stats.pic_objects_without_pic_file }}</td>
                        <td>–</td>
                    </tr>
                    <tr>
                        <td>{{ stats.pic_objects_with_pic_file }}</td>
                        <td>{{ stats.pic_files_with_pic_object }}</td>
                    </tr>
                    <tr>
                        <td>–</td>
                        <td>{{ stats.pic_files_without_pic_object }}</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th scope="col">{{ stats.pic_objects_without_pic_file|add:stats.pic_objects_with_pic_file }}</th>
                        <th scope="col">{{ stats.pic_files_with_pic_object|add:stats.pic_files_without_pic_object }}</th>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="col-2">
            <table class="table table-striped table-dark pic_stats">
                <thead>
                    <tr>
                        <th scope="col">pictures/*</th>
                        <th scope="col">thumbs/*</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>{{ stats.pic_files_without_thumb_file }}</td>
                        <td>–</td>
                    </tr>
                    <tr>
                        <td>{{ stats.pic_files_with_thumb_file }}</td>
                        <td>{{ stats.thumb_files_with_pic_file }}</td>
                    </tr>
                    <tr>
                        <td>–</td>
                        <td>{{ stats.thumb_files_without_pic_file }}</td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <th scope="col">{{ stats.pic_files_without_thumb_file|add:stats.pic_files_with_thumb_file }}</th>
                        <th scope="col">{{ stats.thumb_files_with_pic_file|add:stats.thumb_files_without_pic_file }}</th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <h2 class="mt-4">Disk usage</h2>
            <pre>{{ cleanup_report }}</pre>
        </div>
    </div>
</div>
{% endblock %}

Core/templates/Core/upload.html
{% extends "Core/bs5_base.html" %}
{# load static #}

{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col" style="max-width: 600px;">
            <form method="post" enctype="multipart/form-data">
                <div class="card border-0 shadow-sm">
                    <div class="card-body px-4 pt-4 pb-0">
                        {# csrf_token #}
                        {% include 'Core/inc_bs5_form_simple.html' with form=form only %}
                    </div>
                    <div class="card-footer border-top-0 px-4 py-3">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}